### ISSUE TITLE
Feature Request: Pie Chart

### ISSUE THREAD

**Issue by anton6** [adrixp/aframe-charts-component#1]
As per the title - would be good to have Pie Chart.

Thanks

**Comment by adrixp** [comment]
Hi @anton6 ,

Thanks for submitting your request.

The Pie Chart is in our roadmap and it will be added in the upcoming weeks.

Greetings

**Comment by adrixp** [comment]
Hi @anton6 ,

We have updated aframe-charts-component to version [1.1.0 ](https://github.com/adrixp/aframe-charts-component)

We have added the Pie Chart and some bug bixes.

[Check it out here](https://adrixp.github.io/aframe-charts-component/examples/pieChart/code.html)

Don't hesitate to submit any other submit request.

Greetings
