### ISSUE TITLE
Variable or `a-asset` rather than JSON file

### ISSUE THREAD

**Issue by LukeTOBrien** [adrixp/aframe-charts-component#3]
Hello there,

The chart data requires a JSON file and is used like this:
```HTML
<a-entity charts="dataPoints: ../data/data.json; type: bar"></a-entity>
```
But rather that this I think you could use a variable (`var data = ...`)... Or an `a-asset` [Asset Management](https://aframe.io/docs/0.9.0/core/asset-management-system.html):
```HTML
<a-asset>
    <a-asset-item id="data" src="{'x': 1, 'y': 8, 'z': 0, 'size': 1, 'color': '#ff0000'},
  {'x': -2, 'y': 3, 'z': 1, 'size': 1.5, 'color': '#00ff00'},
  {'x': -1, 'y': 3, 'z': 2, 'size': 1, 'color': '#0000ff'},
  {'x': 2, 'y': 7, 'z': 7, 'size': 1.5, 'color': '#0000ff'},
  {'x': 1, 'y': 6, 'z': 3, 'size': 1, 'color': '#4CC3D9'}"><a-asset-item>
</a-asset>
```

There is also the issue of Ajax, how do you load data from an external server?

**Comment by adrixp** [comment]
Hi @LukeTOBrien 

We are going to add this feature as soon as possible.

Thanks for submitting this issue.

Greetings

**Comment by adrixp** [comment]
Hi,

We have updated aframe-charts-component to version 2.1.6

You can now do the following:

- Option 1:
```HTML
<a-asset>
                <a-asset-item id="data" src='[{"x": 1, "y": 8, "z": 0, "size": 1, "color": "#ff0000"},
                {"x": -2, "y": 3, "z": 1, "size": 1.5, "color": "#00ff00"},
                {"x": -1, "y": 3, "z": 2, "size": 1, "color": "#0000ff"},
                {"x": 2, "y": 7, "z": 7, "size": 1.5, "color": "#0000ff"},
                {"x": 1, "y": 6, "z": 3, "size": 1, "color": "#4CC3D9"}]'>
                    </a-asset-item>
            </a-asset>

<a-entity charts='type: bar; dataPoints: #data; axis_length: 12'></a-entity>
```
- Option 2 (this option solve Ajax issue too):

```HTML
<a-entity id="currentChart" ></a-entity>
```

```JavaScript
let myChart = document.getElementById("currentChart");
let newPoints = [{"x": 1, "y": 8, "z": 0, "size": 1, "color": "#ff0000"},{"x": -2, "y": 3, "z": 1, "size": 1.5, "color": "#00ff00"}];
myChart.setAttribute('charts', {type: "bar", dataPoints: newPoints, axis_length: 12});
```

-Option 3 JSON file:

```HTML
<a-entity charts="dataPoints: ../data/data.json; type: bar"></a-entity>
```

Don't hesitate to submit any other submit issue.

Greetings

**Comment by LukeTOBrien** [comment]
Thank you very much, that's awesome.

A little bit about what I am doing:  
I am creating an app that allows users to create charts, I am creating 2D charts using [Chart.js](https://www.chartjs.org) and I want to use your component to create 3D charts.  
I can already create the [Chart.js config](https://www.chartjs.org/docs/latest/), so this change should allow me to map the data for use with your charts without needing to save an external `.json` file.

**Comment by adrixp** [comment]
I am glad to hear that! If you see any other issue in order to integrate this component let me know.
