### ISSUE TITLE
showing legend causing Three error

### ISSUE THREAD

**Issue by gabrieljbaker** [adrixp/aframe-charts-component#7]
Hi! Really grateful for your excellent work here. This component is absolutely incredible.

One issue I've been having: I believe when I try to show the legend of a chart, I get this error:

THREE.DirectGeometry: Faceless geometries are not supported.

I'm trying to set those properties via Javascript, as such:

 chartEntity.setAttribute("show_legend_info", "");
  chartEntity.setAttribute("show_legend_title", "");

Any ideas?

**Comment by gabrieljbaker** [comment]
PS, after some more testing, it seems like the THREE problem wasn't the issue.

That said, I still can't figure out how to get my legend to appear when I try to set it with setAttribute.  Let me know if anything comes to mind that might help me here.

**Comment by adrixp** [comment]
Hi @gabrieljbaker,

First of all thanks for your words.

The thing is that yout component has one attribute called 'charts' with a JSON value with all the component characteristics.
So, you could do the following:
```JavaScript
let barChart = document.getElementById("barId");
let attrs = barChart.getAttribute('charts');
//Set properties
attrs["show_legend_info"] = true;
attrs["show_legend_title"] = "my title";
attrs["show_legend_position"] = { x: 0, y: 0, z: 0 };
//update the chart
barChart.setAttribute('charts', attrs)
```

Hope it helps,
Greetings
